/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "AgentService_constants.h"

namespace palo {

const AgentServiceConstants g_AgentService_constants;

AgentServiceConstants::AgentServiceConstants() {
}

} // namespace

