/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "DataSinks_constants.h"

namespace palo {

const DataSinksConstants g_DataSinks_constants;

DataSinksConstants::DataSinksConstants() {
}

} // namespace

