/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "Exprs_constants.h"

namespace palo {

const ExprsConstants g_Exprs_constants;

ExprsConstants::ExprsConstants() {
}

} // namespace

