/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "Metrics_constants.h"

namespace palo {

const MetricsConstants g_Metrics_constants;

MetricsConstants::MetricsConstants() {
}

} // namespace

