/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef PaloService_CONSTANTS_H
#define PaloService_CONSTANTS_H

#include "PaloService_types.h"

namespace palo {

class PaloServiceConstants {
 public:
  PaloServiceConstants();

};

extern const PaloServiceConstants g_PaloService_constants;

} // namespace

#endif
