/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef PaloInternalService_CONSTANTS_H
#define PaloInternalService_CONSTANTS_H

#include "PaloInternalService_types.h"

namespace palo {

class PaloInternalServiceConstants {
 public:
  PaloInternalServiceConstants();

  int32_t NUM_NODES_ALL;
  int32_t NUM_NODES_ALL_RACKS;
  int32_t INVALID_PLAN_NODE_ID;
  int64_t DEFAULT_PARTITION_ID;
};

extern const PaloInternalServiceConstants g_PaloInternalService_constants;

} // namespace

#endif
