/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "PaloService_types.h"

#include <algorithm>

namespace palo {

int _kTPaloQueryOptionsValues[] = {
  TPaloQueryOptions::ABORT_ON_ERROR,
  TPaloQueryOptions::MAX_ERRORS,
  TPaloQueryOptions::DISABLE_CODEGEN,
  TPaloQueryOptions::BATCH_SIZE,
  TPaloQueryOptions::MEM_LIMIT,
  TPaloQueryOptions::NUM_NODES,
  TPaloQueryOptions::MAX_SCAN_RANGE_LENGTH,
  TPaloQueryOptions::MAX_IO_BUFFERS,
  TPaloQueryOptions::NUM_SCANNER_THREADS,
  TPaloQueryOptions::QUERY_TIMEOUT,
  TPaloQueryOptions::ALLOW_UNSUPPORTED_FORMATS,
  TPaloQueryOptions::DEFAULT_ORDER_BY_LIMIT,
  TPaloQueryOptions::DEBUG_ACTION,
  TPaloQueryOptions::ABORT_ON_DEFAULT_LIMIT_EXCEEDED,
  TPaloQueryOptions::IS_REPORT_SUCCESS
};
const char* _kTPaloQueryOptionsNames[] = {
  "ABORT_ON_ERROR",
  "MAX_ERRORS",
  "DISABLE_CODEGEN",
  "BATCH_SIZE",
  "MEM_LIMIT",
  "NUM_NODES",
  "MAX_SCAN_RANGE_LENGTH",
  "MAX_IO_BUFFERS",
  "NUM_SCANNER_THREADS",
  "QUERY_TIMEOUT",
  "ALLOW_UNSUPPORTED_FORMATS",
  "DEFAULT_ORDER_BY_LIMIT",
  "DEBUG_ACTION",
  "ABORT_ON_DEFAULT_LIMIT_EXCEEDED",
  "IS_REPORT_SUCCESS"
};
const std::map<int, const char*> _TPaloQueryOptions_VALUES_TO_NAMES(::apache::thrift::TEnumIterator(15, _kTPaloQueryOptionsValues, _kTPaloQueryOptionsNames), ::apache::thrift::TEnumIterator(-1, NULL, NULL));

} // namespace
