/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef BackendService_CONSTANTS_H
#define BackendService_CONSTANTS_H

#include "BackendService_types.h"

namespace palo {

class BackendServiceConstants {
 public:
  BackendServiceConstants();

};

extern const BackendServiceConstants g_BackendService_constants;

} // namespace

#endif
