/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "BackendService_constants.h"

namespace palo {

const BackendServiceConstants g_BackendService_constants;

BackendServiceConstants::BackendServiceConstants() {
}

} // namespace

