/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "PaloInternalService_constants.h"

namespace palo {

const PaloInternalServiceConstants g_PaloInternalService_constants;

PaloInternalServiceConstants::PaloInternalServiceConstants() {
  NUM_NODES_ALL = 0;

  NUM_NODES_ALL_RACKS = -1;

  INVALID_PLAN_NODE_ID = -1;

  DEFAULT_PARTITION_ID = -1LL;

}

} // namespace

