/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "Partitions_constants.h"

namespace palo {

const PartitionsConstants g_Partitions_constants;

PartitionsConstants::PartitionsConstants() {
}

} // namespace

