/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Partitions_CONSTANTS_H
#define Partitions_CONSTANTS_H

#include "Partitions_types.h"

namespace palo {

class PartitionsConstants {
 public:
  PartitionsConstants();

};

extern const PartitionsConstants g_Partitions_constants;

} // namespace

#endif
