/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef PlanNodes_CONSTANTS_H
#define PlanNodes_CONSTANTS_H

#include "PlanNodes_types.h"

namespace palo {

class PlanNodesConstants {
 public:
  PlanNodesConstants();

};

extern const PlanNodesConstants g_PlanNodes_constants;

} // namespace

#endif
