/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Planner_TYPES_H
#define Planner_TYPES_H

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include <thrift/cxxfunctional.h>
#include "Types_types.h"
#include "Exprs_types.h"
#include "DataSinks_types.h"
#include "PlanNodes_types.h"
#include "Partitions_types.h"


namespace palo {

typedef struct _TPlanFragment__isset {
  _TPlanFragment__isset() : plan(false), output_exprs(false), output_sink(false) {}
  bool plan;
  bool output_exprs;
  bool output_sink;
} _TPlanFragment__isset;

class TPlanFragment {
 public:

  static const char* ascii_fingerprint; // = "A0C07048D48A95598D1A8976894FAB34";
  static const uint8_t binary_fingerprint[16]; // = {0xA0,0xC0,0x70,0x48,0xD4,0x8A,0x95,0x59,0x8D,0x1A,0x89,0x76,0x89,0x4F,0xAB,0x34};

  TPlanFragment() {
  }

  virtual ~TPlanFragment() throw() {}

   ::palo::TPlan plan;
  std::vector< ::palo::TExpr>  output_exprs;
   ::palo::TDataSink output_sink;
   ::palo::TDataPartition partition;

  _TPlanFragment__isset __isset;

  void __set_plan(const  ::palo::TPlan& val) {
    plan = val;
    __isset.plan = true;
  }

  void __set_output_exprs(const std::vector< ::palo::TExpr> & val) {
    output_exprs = val;
    __isset.output_exprs = true;
  }

  void __set_output_sink(const  ::palo::TDataSink& val) {
    output_sink = val;
    __isset.output_sink = true;
  }

  void __set_partition(const  ::palo::TDataPartition& val) {
    partition = val;
  }

  bool operator == (const TPlanFragment & rhs) const
  {
    if (__isset.plan != rhs.__isset.plan)
      return false;
    else if (__isset.plan && !(plan == rhs.plan))
      return false;
    if (__isset.output_exprs != rhs.__isset.output_exprs)
      return false;
    else if (__isset.output_exprs && !(output_exprs == rhs.output_exprs))
      return false;
    if (__isset.output_sink != rhs.__isset.output_sink)
      return false;
    else if (__isset.output_sink && !(output_sink == rhs.output_sink))
      return false;
    if (!(partition == rhs.partition))
      return false;
    return true;
  }
  bool operator != (const TPlanFragment &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TPlanFragment & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

void swap(TPlanFragment &a, TPlanFragment &b);

typedef struct _TScanRangeLocation__isset {
  _TScanRangeLocation__isset() : volume_id(true), backend_id(false) {}
  bool volume_id;
  bool backend_id;
} _TScanRangeLocation__isset;

class TScanRangeLocation {
 public:

  static const char* ascii_fingerprint; // = "93D9FEDEBFFC7D3F939AAAC1BED16FA1";
  static const uint8_t binary_fingerprint[16]; // = {0x93,0xD9,0xFE,0xDE,0xBF,0xFC,0x7D,0x3F,0x93,0x9A,0xAA,0xC1,0xBE,0xD1,0x6F,0xA1};

  TScanRangeLocation() : volume_id(-1), backend_id(0) {
  }

  virtual ~TScanRangeLocation() throw() {}

   ::palo::TNetworkAddress server;
  int32_t volume_id;
  int64_t backend_id;

  _TScanRangeLocation__isset __isset;

  void __set_server(const  ::palo::TNetworkAddress& val) {
    server = val;
  }

  void __set_volume_id(const int32_t val) {
    volume_id = val;
    __isset.volume_id = true;
  }

  void __set_backend_id(const int64_t val) {
    backend_id = val;
    __isset.backend_id = true;
  }

  bool operator == (const TScanRangeLocation & rhs) const
  {
    if (!(server == rhs.server))
      return false;
    if (__isset.volume_id != rhs.__isset.volume_id)
      return false;
    else if (__isset.volume_id && !(volume_id == rhs.volume_id))
      return false;
    if (__isset.backend_id != rhs.__isset.backend_id)
      return false;
    else if (__isset.backend_id && !(backend_id == rhs.backend_id))
      return false;
    return true;
  }
  bool operator != (const TScanRangeLocation &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TScanRangeLocation & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

void swap(TScanRangeLocation &a, TScanRangeLocation &b);

typedef struct _TScanRangeLocations__isset {
  _TScanRangeLocations__isset() : locations(false) {}
  bool locations;
} _TScanRangeLocations__isset;

class TScanRangeLocations {
 public:

  static const char* ascii_fingerprint; // = "F87F75BEF7D287E4A74319C93DABC9F2";
  static const uint8_t binary_fingerprint[16]; // = {0xF8,0x7F,0x75,0xBE,0xF7,0xD2,0x87,0xE4,0xA7,0x43,0x19,0xC9,0x3D,0xAB,0xC9,0xF2};

  TScanRangeLocations() {
  }

  virtual ~TScanRangeLocations() throw() {}

   ::palo::TScanRange scan_range;
  std::vector<TScanRangeLocation>  locations;

  _TScanRangeLocations__isset __isset;

  void __set_scan_range(const  ::palo::TScanRange& val) {
    scan_range = val;
  }

  void __set_locations(const std::vector<TScanRangeLocation> & val) {
    locations = val;
  }

  bool operator == (const TScanRangeLocations & rhs) const
  {
    if (!(scan_range == rhs.scan_range))
      return false;
    if (!(locations == rhs.locations))
      return false;
    return true;
  }
  bool operator != (const TScanRangeLocations &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TScanRangeLocations & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

void swap(TScanRangeLocations &a, TScanRangeLocations &b);

} // namespace

#endif
