/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "Planner_constants.h"

namespace palo {

const PlannerConstants g_Planner_constants;

PlannerConstants::PlannerConstants() {
}

} // namespace

